/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concessionario;

import java.sql.Connection;

import concessionario.db.ConnectionProvider;

public class Concessionario {

    public static void main(String[] args) {
        final ConnectionProvider connectionProvider = new ConnectionProvider("root","nretIOGbiiuhDE789", "concessionario");
        final Connection connection = connectionProvider.getMySQLConnection();
    }
}
